### ISSUE TITLE
smtplib.SMTPAuthenticationError

### ISSUE THREAD

**Issue by darkhacknet** [s4msecurity/SMail#1]
Hi there, 

I think that this is an issue due to my email info its correct. Please help us, taking a look. 

smtplib.SMTPAuthenticationError: (535, b'5.7.8 Error: authentication failed: This user does not have access rights to this service 1667632359-ZBivLW8qVk-CZgGKw6i')

Thanks in advance.

**Comment by s4msecurity** [comment]
Hello,
Firstly thank you for you say me  this error.

I wrote warning in this script. 
This python script cant open authenticate because Google not supported 3'rd parties software. Before may 30 2022 it worked.

If you want review: https://support.google.com/accounts/answer/6010255?hl=en&utm_source=google-account&utm_medium=profile-less-secure-apps-card

For this I supported Yandex. If you want try Yandex e-mail.

**Comment by s4msecurity** [comment]
Hello there,

If you enough my answer, please do you close issue. Thank you.

**Comment by darkhacknet** [comment]
> Hello,
> 
> Firstly thank you for you say me  this error.
> 
> 
> 
> I wrote warning in this script. 
> 
> This python script cant open authenticate because Google not supported 3'rd parties software. Before may 30 2022 it worked.
> 
> 
> 
> If you want review: https://support.google.com/accounts/answer/6010255?hl=en&utm_source=google-account&utm_medium=profile-less-secure-apps-card
> 
> 
> 
> For this I supported Yandex. If you want try Yandex e-mail.
> 
> 

Hey bro thanks for take a look into this, but I'm talking about yandex.. are you able to make this work using yandex ? Thanks

**Comment by s4msecurity** [comment]
Hello there,
I reviewed this error. Problem Yandex mail server. The new added a app for mail/Pop/Imap. You need doing Yandex re-configuration.

Please first this go link [Yandex Email Clients Settings](https://mail.yandex.com/?dpda=yes&uid=1715321732#setup/client) then doing a configuration 3'rd party software settings.

![Email Clients](https://user-images.githubusercontent.com/81925511/202921977-b96df16e-94ec-49f7-9d7a-94a121f360e6.png)

Add Yandex app new a password for 3'rd party software mail client.
Add a password for 3'rd party software: [Yandex App Password List](https://id.yandex.com/profile/apppasswords-list)

Step 1
![Email Clients 2](https://user-images.githubusercontent.com/81925511/202922201-f44bada8-4d8d-4033-9242-d6363aa91ed1.png)

Step 2
![202922219-fb172c80-0d22-49c6-afed-eb9e83ffe498](https://user-images.githubusercontent.com/81925511/202922253-0b6b3332-538d-4243-a676-46c4d8965968.png)

And follow step 2. As you can see in the picture below, you will add a new password.
After step 2, Yandex will direct you and give you a different password. Please do not lose the password.

![Ekran görüntüsü 2022-11-20 223618](https://user-images.githubusercontent.com/81925511/202922421-17950949-29a5-44e6-ac14-49e230b94696.png)

This Python script works me too.

![Ekran görüntüsü 2022-11-20 224222](https://user-images.githubusercontent.com/81925511/202922577-b3dab66c-c52e-4503-ac8d-ada6420168cd.png)

If you want a more info, please review this: https://yandex.com/support/mail/mail-clients/others.html
Please try a this methods. If the work this Python script please close issue.
**A big thanks for you say me this error.**

**Comment by darkhacknet** [comment]
> Hello there,
> 
> I reviewed this error. Problem Yandex mail server. The new added a app for mail/Pop/Imap. You need doing Yandex re-configuration.
> 
> 
> 
> Please first this go link [Yandex Email Clients Settings](https://mail.yandex.com/?dpda=yes&uid=1715321732#setup/client) then doing a configuration 3'rd party software settings.
> 
> 
> 
> ![Email Clients](https://user-images.githubusercontent.com/81925511/202921977-b96df16e-94ec-49f7-9d7a-94a121f360e6.png)
> 
> 
> 
> Add Yandex app new a password for 3'rd party software mail client.
> 
> Add a password for 3'rd party software: [Yandex App Password List](https://id.yandex.com/profile/apppasswords-list)
> 
> 
> 
> Step 1
> 
> ![Email Clients 2](https://user-images.githubusercontent.com/81925511/202922201-f44bada8-4d8d-4033-9242-d6363aa91ed1.png)
> 
> 
> 
> Step 2
> 
> ![202922219-fb172c80-0d22-49c6-afed-eb9e83ffe498](https://user-images.githubusercontent.com/81925511/202922253-0b6b3332-538d-4243-a676-46c4d8965968.png)
> 
> 
> 
> And follow step 2. As you can see in the picture below, you will add a new password.
> 
> After step 2, Yandex will direct you and give you a different password. Please do not lose the password.
> 
> 
> 
> ![Ekran görüntüsü 2022-11-20 223618](https://user-images.githubusercontent.com/81925511/202922421-17950949-29a5-44e6-ac14-49e230b94696.png)
> 
> 
> 
> This Python script works me too.
> 
> 
> 
> ![Ekran görüntüsü 2022-11-20 224222](https://user-images.githubusercontent.com/81925511/202922577-b3dab66c-c52e-4503-ac8d-ada6420168cd.png)
> 
> 
> 
> If you want a more info, please review this: https://yandex.com/support/mail/mail-clients/others.html
> 
> Please try a this methods. If the work this Python script please close issue.
> 
> **A big thanks for you say me this error.**
> 
> 

Omg man thanks a lot for this detailed guide.

**Comment by darkhacknet** [comment]
> Hello there, I reviewed this error. Problem Yandex mail server. The new added a app for mail/Pop/Imap. You need doing Yandex re-configuration.
> 
> Please first this go link [Yandex Email Clients Settings](https://mail.yandex.com/?dpda=yes&uid=1715321732#setup/client) then doing a configuration 3'rd party software settings.
> 
> ![Email Clients](https://user-images.githubusercontent.com/81925511/202921977-b96df16e-94ec-49f7-9d7a-94a121f360e6.png)
> 
> Add Yandex app new a password for 3'rd party software mail client. Add a password for 3'rd party software: [Yandex App Password List](https://id.yandex.com/profile/apppasswords-list)
> 
> Step 1 ![Email Clients 2](https://user-images.githubusercontent.com/81925511/202922201-f44bada8-4d8d-4033-9242-d6363aa91ed1.png)
> 
> Step 2 ![202922219-fb172c80-0d22-49c6-afed-eb9e83ffe498](https://user-images.githubusercontent.com/81925511/202922253-0b6b3332-538d-4243-a676-46c4d8965968.png)
> 
> And follow step 2. As you can see in the picture below, you will add a new password. After step 2, Yandex will direct you and give you a different password. Please do not lose the password.
> 
> ![Ekran görüntüsü 2022-11-20 223618](https://user-images.githubusercontent.com/81925511/202922421-17950949-29a5-44e6-ac14-49e230b94696.png)
> 
> This Python script works me too.
> 
> ![Ekran görüntüsü 2022-11-20 224222](https://user-images.githubusercontent.com/81925511/202922577-b3dab66c-c52e-4503-ac8d-ada6420168cd.png)
> 
> If you want a more info, please review this: https://yandex.com/support/mail/mail-clients/others.html Please try a this methods. If the work this Python script please close issue. **A big thanks for you say me this error.**

Hello again, 

could you please tell me how to avoid this error ? is not related directly with your script. But will help :D 

(554, b'5.7.1 Message rejected under suspicion of SPAM;

It happens any time that I try to send an email. 

Thanks !

**Comment by s4msecurity** [comment]
Hello again,

If you send to the same address repeatedly, it blocks it within 5 minutes.
Please wait for a while to try again after you send an email spam. This is a case with the Yandex Mail service.

I will develop this Python script over time and instead attack from different mail service servers.

**Google does not support unlicensed apps. Yandex checks the sent mails.**

This Python script prevents it from being detected by the receiver, but there is no escape from the service being sent.

I present it to your information.
